# Generated by Django 4.2.11 on 2025-09-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
