# Generated by Django 4.2.11 on 2025-09-02 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '__first__'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('message_type', models.CharField(choices=[('motivational', 'Motivational'), ('reminder', 'Reminder'), ('congratulations', 'Congratulations'), ('check_in', 'Check-in'), ('educational', 'Educational'), ('custom', 'Custom')], max_length=20)),
                ('available_variables', models.JSONField(default=list, help_text='Available template variables like {client_name}, {goal}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='trainers.trainerprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EngagementMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('motivational', 'Motivational'), ('reminder', 'Reminder'), ('congratulations', 'Congratulations'), ('check_in', 'Check-in'), ('educational', 'Educational'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_prompt_used', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='clients.clientprofile')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='trainers.trainerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
