# Generated by Django 4.2.11 on 2025-09-02 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardiovascular'), ('flexibility', 'Flexibility'), ('balance', 'Balance'), ('functional', 'Functional'), ('sports', 'Sports Specific')], max_length=20)),
                ('equipment_needed', models.CharField(choices=[('bodyweight', 'Bodyweight'), ('dumbbells', 'Dumbbells'), ('barbell', 'Barbell'), ('resistance_bands', 'Resistance Bands'), ('kettlebell', 'Kettlebell'), ('machine', 'Machine'), ('cardio_equipment', 'Cardio Equipment'), ('minimal', 'Minimal Equipment')], default='bodyweight', max_length=30)),
                ('muscle_groups', models.CharField(help_text='Comma-separated muscle groups', max_length=200)),
                ('setup_instructions', models.TextField(help_text='How to set up the exercise')),
                ('execution_steps', models.TextField(help_text='Step-by-step execution')),
                ('safety_tips', models.TextField(blank=True)),
                ('demonstration_video_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('modifications', models.TextField(blank=True, help_text='Easier/harder variations')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_weeks', models.PositiveIntegerField(default=4, help_text='Plan duration in weeks')),
                ('workout_structure', models.JSONField(default=dict, help_text='Weekly workout structure')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ai_enhanced', models.BooleanField(default=False)),
                ('ai_suggestions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='clients.clientprofile')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='trainers.trainerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
