# Generated by Django 4.2.11 on 2025-09-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='start_date',
        ),
    ]
