# Generated by Django 4.2.11 on 2025-09-14 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_workoutschedule_client_and_more'),
        ('workouts', '0002_remove_workoutplan_duration_weeks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('exercise_name', models.CharField(max_length=120)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_progress', to='clients.clientprofile')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='workouts.workoutplan')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'day'], name='workouts_ex_client__a90722_idx'), models.Index(fields=['workout_plan', 'day'], name='workouts_ex_workout_8b90b7_idx')],
                'unique_together': {('client', 'workout_plan', 'day', 'exercise_name')},
            },
        ),
    ]
