# Generated by Django 4.2.11 on 2025-09-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_exercise_execution_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='execution_steps',
            field=models.TextField(blank=True, help_text='Step-by-step execution', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_groups',
            field=models.CharField(blank=True, help_text='Comma-separated muscle groups', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='setup_instructions',
            field=models.TextField(blank=True, help_text='How to set up the exercise', null=True),
        ),
    ]
