# Generated by Django 4.2.11 on 2025-09-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_exercise_execution_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
