# Generated by Django 4.2.11 on 2025-09-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_alter_trainerprofile_bio'),
        ('workouts', '0006_exercise_is_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='trainers.trainerprofile'),
        ),
    ]
