# Generated by Django 4.2.11 on 2025-09-03 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainerprofile_is_verified'),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('calories_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('protein_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carbs_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fat_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='trainers.trainerprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
