# Generated by Django 4.2.11 on 2025-09-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_trainerfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerfood',
            name='category',
            field=models.CharField(choices=[('grains', 'Grains & Cereals'), ('legumes', 'Legumes'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('meat', 'Meat & Poultry'), ('dairy', 'Dairy'), ('spices', 'Spices & Herbs'), ('beverages', 'Beverages'), ('traditional_dishes', 'Traditional Dishes')], max_length=30),
        ),
    ]
