# Generated by Django 4.2.11 on 2025-09-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_trainerfood_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerfood',
            name='cultural_significance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainerfood',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainerfood',
            name='fiber_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='trainerfood',
            name='is_fasting_friendly',
            field=models.BooleanField(default=False, help_text='Orthodox fasting compatible'),
        ),
        migrations.AddField(
            model_name='trainerfood',
            name='is_gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainerfood',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainerfood',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainerfood',
            name='preparation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainerfood',
            name='seasonal_availability',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='trainerfood',
            name='category',
            field=models.CharField(blank=True, choices=[('grains', 'Grains & Cereals'), ('legumes', 'Legumes'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('meat', 'Meat & Poultry'), ('dairy', 'Dairy'), ('spices', 'Spices & Herbs'), ('beverages', 'Beverages'), ('traditional_dishes', 'Traditional Dishes'), ('other', 'Other')], max_length=30),
        ),
    ]
