# Generated by Django 4.2.11 on 2025-09-14 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 9, 14, 22, 25, 46, 721222), null=True),
        ),
    ]
