from django.core.management.base import BaseCommand
from django.utils import timezone
from apps.workouts.models import Exercise  # adjust path to your Exercise model

class Command(BaseCommand):
    help = "Seed database with default exercises"

    def handle(self, *args, **kwargs):
        exercises = [
            # ---------------- Bodyweight (10) ----------------
            {
                "name": "Push-up",
                "description": "A classic bodyweight exercise to strengthen chest, shoulders, and triceps.",
                "category": "strength",
                "equipment_needed": "bodyweight",
                "muscle_groups": "Chest, Triceps, Shoulders, Core",
                "execution_steps": "Keep body straight, lower until chest nearly touches floor, push back up.",
                "safety_tips": "Avoid arching lower back, keep core tight.",
                "demonstration_video_url": "https://www.youtube.com/watch?v=_l3ySVKYVJ8",
                "difficulty_level": "beginner",
            },
            {
                "name": "Squat",
                "description": "Strengthens legs and glutes using bodyweight.",
                "category": "strength",
                "equipment_needed": "bodyweight",
                "muscle_groups": "Quadriceps, Glutes, Hamstrings",
                "execution_steps": "Lower hips back and down, keep knees aligned with toes, return to standing.",
                "demonstration_video_url": "https://www.youtube.com/watch?v=YaXPRqUwItQ",
                "difficulty_level": "beginner",
            },
            {
                "name": "Lunges",
                "description": "Single-leg exercise to improve balance and strengthen lower body.",
                "category": "strength",
                "equipment_needed": "bodyweight",
                "muscle_groups": "Quadriceps, Glutes, Hamstrings",
                "demonstration_video_url": "https://www.youtube.com/watch?v=QOVaHwm-Q6U",
                "difficulty_level": "beginner",
            },
            {
                "name": "Burpees",
                "description": "Full-body explosive movement combining squat, plank, and jump.",
                "category": "cardio",
                "equipment_needed": "bodyweight",
                "muscle_groups": "Full Body",
                "demonstration_video_url": "https://www.youtube.com/watch?v=qLBImHhCXSw",
                "difficulty_level": "intermediate",
            },
            {
                "name": "Plank",
                "description": "Isometric core strength exercise.",
                "category": "strength",
                "equipment_needed": "bodyweight",
                "muscle_groups": "Core, Shoulders",
                "demonstration_video_url": "https://www.youtube.com/watch?v=B296mZDhrP4",
                "difficulty_level": "beginner",
            },
            {
                "name": "Mountain Climbers",
                "description": "Cardio move that engages the entire body.",
                "category": "cardio",
                "equipment_needed": "bodyweight",
                "muscle_groups": "Core, Shoulders, Legs",
                "demonstration_video_url": "https://www.youtube.com/watch?v=nmwgirgXLYM",
                "difficulty_level": "intermediate",
            },
            {
                "name": "Glute Bridge",
                "description": "Targets glutes and lower back.",
                "category": "strength",
                "equipment_needed": "bodyweight",
                "muscle_groups": "Glutes, Hamstrings, Core",
                "demonstration_video_url": "https://www.youtube.com/watch?v=wPM8icPu6H8",
                "difficulty_level": "beginner",
            },
            {
                "name": "Jumping Jacks",
                "description": "Basic warm-up exercise to increase heart rate.",
                "category": "cardio",
                "equipment_needed": "bodyweight",
                "muscle_groups": "Full Body",
                "demonstration_video_url": "https://www.youtube.com/watch?v=UpH7rm0cYbM",
                "difficulty_level": "beginner",
            },
            {
                "name": "Pull-up",
                "description": "Upper body exercise requiring a bar.",
                "category": "strength",
                "equipment_needed": "minimal",
                "muscle_groups": "Back, Biceps, Shoulders",
                "demonstration_video_url": "https://www.youtube.com/watch?v=eGo4IYlbE5g",
                "difficulty_level": "advanced",
            },
            {
                "name": "Dips (Chair/Bench)",
                "description": "Bodyweight triceps exercise.",
                "category": "strength",
                "equipment_needed": "minimal",
                "muscle_groups": "Triceps, Shoulders, Chest",
                "demonstration_video_url": "https://www.youtube.com/watch?v=6kALZikXxLc",
                "difficulty_level": "intermediate",
            },

            # ---------------- Gym Exercises (20) ----------------
            {
                "name": "Barbell Bench Press",
                "description": "Classic chest strength exercise.",
                "category": "strength",
                "equipment_needed": "barbell",
                "muscle_groups": "Chest, Triceps, Shoulders",
                "demonstration_video_url": "https://www.youtube.com/watch?v=rT7DgCr-3pg",
                "difficulty_level": "intermediate",
            },
            {
                "name": "Barbell Squat",
                "description": "Key compound leg exercise.",
                "category": "strength",
                "equipment_needed": "barbell",
                "muscle_groups": "Quadriceps, Glutes, Hamstrings, Core",
                "demonstration_video_url": "https://www.youtube.com/watch?v=SW_C1A-rejs",
                "difficulty_level": "intermediate",
            },
            {
                "name": "Deadlift",
                "description": "Full-body pulling exercise.",
                "category": "strength",
                "equipment_needed": "barbell",
                "muscle_groups": "Back, Glutes, Hamstrings, Core",
                "demonstration_video_url": "https://www.youtube.com/watch?v=op9kVnSso6Q",
                "difficulty_level": "advanced",
            },
            {
                "name": "Overhead Press",
                "description": "Shoulder and triceps pressing exercise.",
                "category": "strength",
                "equipment_needed": "barbell",
                "muscle_groups": "Shoulders, Triceps, Core",
                "demonstration_video_url": "https://www.youtube.com/watch?v=B-aVuyhvLHU",
                "difficulty_level": "intermediate",
            },
            {
                "name": "Lat Pulldown",
                "description": "Pulling exercise targeting lats.",
                "category": "strength",
                "equipment_needed": "machine",
                "muscle_groups": "Back, Biceps, Shoulders",
                "demonstration_video_url": "https://www.youtube.com/watch?v=CAwf7n6Luuc",
                "difficulty_level": "beginner",
            },
            {
                "name": "Seated Row",
                "description": "Machine row for back muscles.",
                "category": "strength",
                "equipment_needed": "machine",
                "muscle_groups": "Back, Biceps, Rear Delts",
                "demonstration_video_url": "https://www.youtube.com/watch?v=GZbfZ033f74",
                "difficulty_level": "beginner",
            },
            {
                "name": "Dumbbell Bicep Curl",
                "description": "Isolation exercise for arms.",
                "category": "strength",
                "equipment_needed": "dumbbells",
                "muscle_groups": "Biceps",
                "demonstration_video_url": "https://www.youtube.com/watch?v=ykJmrZ5v0Oo",
                "difficulty_level": "beginner",
            },
            {
                "name": "Dumbbell Shoulder Press",
                "description": "Strengthens shoulders and triceps.",
                "category": "strength",
                "equipment_needed": "dumbbells",
                "muscle_groups": "Shoulders, Triceps",
                "demonstration_video_url": "https://www.youtube.com/watch?v=B-aVuyhvLHU",
                "difficulty_level": "intermediate",
            },
            {
                "name": "Dumbbell Chest Fly",
                "description": "Opens chest muscles.",
                "category": "strength",
                "equipment_needed": "dumbbells",
                "muscle_groups": "Chest",
                "demonstration_video_url": "https://www.youtube.com/watch?v=eozdVDA78K0",
                "difficulty_level": "beginner",
            },
            {
                "name": "Dumbbell Lunges",
                "description": "Weighted lunge for legs.",
                "category": "strength",
                "equipment_needed": "dumbbells",
                "muscle_groups": "Legs, Glutes",
                "demonstration_video_url": "https://www.youtube.com/watch?v=QOVaHwm-Q6U",
                "difficulty_level": "intermediate",
            },
            {
                "name": "Leg Press",
                "description": "Machine-based leg exercise.",
                "category": "strength",
                "equipment_needed": "machine",
                "muscle_groups": "Quadriceps, Glutes, Hamstrings",
                "demonstration_video_url": "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
                "difficulty_level": "beginner",
            },
            {
                "name": "Leg Curl (Machine)",
                "description": "Isolation exercise for hamstrings.",
                "category": "strength",
                "equipment_needed": "machine",
                "muscle_groups": "Hamstrings",
                "demonstration_video_url": "https://www.youtube.com/watch?v=1Tq3QdYUuHs",
                "difficulty_level": "beginner",
            },
            {
                "name": "Calf Raises (Machine)",
                "description": "Strengthens calves.",
                "category": "strength",
                "equipment_needed": "machine",
                "muscle_groups": "Calves",
                "demonstration_video_url": "https://www.youtube.com/watch?v=YMmgqO8Jo-k",
                "difficulty_level": "beginner",
            },
            {
                "name": "Cable Tricep Pushdown",
                "description": "Isolation exercise for triceps.",
                "category": "strength",
                "equipment_needed": "machine",
                "muscle_groups": "Triceps",
                "demonstration_video_url": "https://www.youtube.com/watch?v=2-LAMcpzODU",
                "difficulty_level": "beginner",
            },
            {
                "name": "Cable Face Pull",
                "description": "Posterior deltoid and upper back exercise.",
                "category": "strength",
                "equipment_needed": "machine",
                "muscle_groups": "Rear Delts, Upper Back",
                "demonstration_video_url": "https://www.youtube.com/watch?v=rep-qVOkqgk",
                "difficulty_level": "intermediate",
            },
            {
                "name": "Kettlebell Swing",
                "description": "Explosive hip hinge exercise.",
                "category": "functional",
                "equipment_needed": "kettlebell",
                "muscle_groups": "Glutes, Hamstrings, Core, Shoulders",
                "demonstration_video_url": "https://www.youtube.com/watch?v=YSxHifyIu2U",
                "difficulty_level": "intermediate",
            },
            {
                "name": "Treadmill Running",
                "description": "Cardio exercise on treadmill.",
                "category": "cardio",
                "equipment_needed": "cardio_equipment",
                "muscle_groups": "Legs, Cardiovascular System",
                "demonstration_video_url": "https://www.youtube.com/watch?v=Np89KwV2GvI",
                "difficulty_level": "beginner",
            },
            {
                "name": "Stationary Bike",
                "description": "Low-impact cardio exercise.",
                "category": "cardio",
                "equipment_needed": "cardio_equipment",
                "muscle_groups": "Legs, Cardiovascular System",
                "demonstration_video_url": "https://www.youtube.com/watch?v=1fBhL3M1pZs",
                "difficulty_level": "beginner",
            },
            {
                "name": "Elliptical Trainer",
                "description": "Full-body cardio exercise.",
                "category": "cardio",
                "equipment_needed": "cardio_equipment",
                "muscle_groups": "Full Body, Cardiovascular System",
                "demonstration_video_url": "https://www.youtube.com/watch?v=hmFQqjMF_f0",
                "difficulty_level": "beginner",
            },
            {
                "name": "Rowing Machine",
                "description": "Cardio and back strength exercise.",
                "category": "cardio",
                "equipment_needed": "cardio_equipment",
                "muscle_groups": "Back, Legs, Core",
                "demonstration_video_url": "https://www.youtube.com/watch?v=3NjGZIX9s3A",
                "difficulty_level": "intermediate",
            },
        ]

        for ex in exercises:
            Exercise.objects.get_or_create(
                name=ex["name"],
                defaults={
                    "description": ex["description"],
                    "category": ex["category"],
                    "equipment_needed": ex["equipment_needed"],
                    "muscle_groups": ex.get("muscle_groups", ""),
                    "execution_steps": ex.get("execution_steps", ""),
                    "safety_tips": ex.get("safety_tips", ""),
                    "demonstration_video_url": ex["demonstration_video_url"],
                    "difficulty_level": ex["difficulty_level"],
                    "is_global": True,
                    "is_active": True,
                    "created_at": timezone.now(),
                }
            )

        self.stdout.write(self.style.SUCCESS("✅ Seeded exercises successfully!"))
