# Generated by Django 4.2.11 on 2025-09-02 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('specializations', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('strength', 'Strength Training'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('rehabilitation', 'Rehabilitation'), ('sports_specific', 'Sports Specific'), ('general_fitness', 'General Fitness')], default='general_fitness', max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('certifications', models.TextField(blank=True, help_text='List your certifications')),
                ('package', models.CharField(choices=[('basic', 'Basic - $29/month'), ('pro', 'Pro - $79/month'), ('enterprise', 'Enterprise - $199/month')], default='basic', max_length=20)),
                ('package_start_date', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='trainer_logos/')),
                ('brand_color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_accepting_clients', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
