# Generated by Django 4.2.11 on 2025-09-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
