# Generated by Django 4.2.11 on 2025-09-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainerprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='bio',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='business_name',
            field=models.CharField(max_length=100),
        ),
    ]
