# Generated by Django 4.2.11 on 2025-09-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_trainerprofile_is_paid_alter_trainerprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='bio',
            field=models.TextField(help_text='Write a brief professional bio (max 500 characters). Highlight your expertise, achievements, and what makes you unique.', max_length=500),
        ),
    ]
