# Generated by Django 4.2.11 on 2025-09-02 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('strength', 'Build Strength'), ('endurance', 'Improve Endurance'), ('flexibility', 'Increase Flexibility'), ('general_fitness', 'General Fitness'), ('rehabilitation', 'Rehabilitation'), ('sports_performance', 'Sports Performance')], default='general_fitness', max_length=30)),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in cm', null=True)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Target weight in kg', max_digits=5, null=True)),
                ('dietary_restrictions', models.CharField(choices=[('none', 'No Restrictions'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('gluten_free', 'Gluten Free'), ('dairy_free', 'Dairy Free'), ('diabetic', 'Diabetic Friendly'), ('low_sodium', 'Low Sodium')], default='none', max_length=30)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions or injuries')),
                ('allergies', models.TextField(blank=True, help_text='Food allergies or intolerances')),
                ('preferred_workout_days', models.CharField(blank=True, help_text='e.g., Monday, Wednesday, Friday', max_length=100)),
                ('workout_duration_preference', models.PositiveIntegerField(default=60, help_text='Preferred workout duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Trainer notes about client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='trainers.trainerprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
