# Generated by Django 4.2.11 on 2025-09-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_timeblock_clientprofile_weekly_sessions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutschedule',
            name='client',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='time_block',
        ),
        migrations.DeleteModel(
            name='TimeBlock',
        ),
        migrations.DeleteModel(
            name='WorkoutSchedule',
        ),
        migrations.DeleteModel(
            name='WorkoutSession',
        ),
    ]
