# Generated by Django 4.2.11 on 2025-09-06 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutschedule',
            name='default_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='default_start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
