# Generated by Django 4.2.11 on 2025-09-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_workoutschedule_default_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
